### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by REBELinBLUE** [huyng/bashmarks#53]
When I type `g <tab>` I get `g 1:IR_deployer`. My `~/.sdirs` contains `export DIR_deployer="$HOME/Sites/deployer"`

**Comment by bertnp** [comment]
I had this issue too. Turned out it was because I had grep aliased to always output line numbers (with the -n option) and bashmarks.sh doesn't expect grep output to be formatted that way. To fix the issue, I just modified my grep alias by removing the -n option. However, another fix that doesn't require changed your grep alias would be to enclose the instances of the grep command in the _l function in bashmarks.sh (line 113) with double quotes (ie, replace grep with "grep") so that the alias is not invoked.

**Comment by REBELinBLUE** [comment]
Oh yeah, forgot about this, I realised that a long time ago
